import java.sql.*;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Addinfo_page extends javax.swing.JFrame {
   
    /**
     * Creates new form Addinfo_page
     */
    public Addinfo_page() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        DP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nm1 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        s1 = new javax.swing.JTextField();
        rb2 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        ct1 = new javax.swing.JTextField();
        m1 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        img = new javax.swing.JLabel();
        AP = new javax.swing.JPanel();
        AL = new javax.swing.JLabel();
        REP = new javax.swing.JPanel();
        REL = new javax.swing.JLabel();
        RP = new javax.swing.JPanel();
        RL = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        imt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration page");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 7));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 770));
        jPanel1.setLayout(null);

        DP.setBackground(new java.awt.Color(0, 51, 51));
        DP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DPMouseDragged(evt);
            }
        });
        DP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DPMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTER ");

        javax.swing.GroupLayout DPLayout = new javax.swing.GroupLayout(DP);
        DP.setLayout(DPLayout);
        DPLayout.setHorizontalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351))
        );
        DPLayout.setVerticalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(DP);
        DP.setBounds(7, 7, 1266, 121);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(581, 300));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" ID NO");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" CLASS");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" DOB");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" SCHOOL");

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" BOARD");

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" ADDRESS");

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" MOBILE NO");

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" CITY");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" E-mail ID");

        nm1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nm1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        nm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm1ActionPerformed(evt);
            }
        });
        nm1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nm1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nm1KeyTyped(evt);
            }
        });

        c1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        c1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        d1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        d1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        s1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        s1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        rb2.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        rb2.setForeground(new java.awt.Color(255, 255, 255));
        rb2.setText("ICSE");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        rb1.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        rb1.setForeground(new java.awt.Color(255, 255, 255));
        rb1.setText("CBSE");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        ta1.setColumns(20);
        ta1.setRows(5);
        ta1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jScrollPane1.setViewportView(ta1);

        ct1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        m1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });

        e1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        e1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                e1KeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("GENDER");

        rb3.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(rb3);
        rb3.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        rb3.setForeground(new java.awt.Color(255, 255, 255));
        rb3.setText("MALE");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        rb4.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(rb4);
        rb4.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        rb4.setForeground(new java.awt.Color(255, 255, 255));
        rb4.setText("FEMALE");

        jLabel14.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PINCODE");

        p1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" NAME");

        id1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        id1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        id1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ct1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(c1)
                                        .addGap(143, 143, 143))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nm1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(73, 73, 73)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(rb4))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rb3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rb4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(13, 13, 13)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ct1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nm1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(17, 139, 937, 613);

        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel1.add(img);
        img.setBounds(980, 139, 254, 238);

        AP.setBackground(new java.awt.Color(255, 255, 255));
        AP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        AP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AP.setPreferredSize(new java.awt.Dimension(180, 53));

        AL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        AL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AL.setText("ADD PHOTO");
        AL.setPreferredSize(new java.awt.Dimension(180, 53));
        AL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ALMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ALMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ALMouseExited(evt);
            }
        });

        javax.swing.GroupLayout APLayout = new javax.swing.GroupLayout(AP);
        AP.setLayout(APLayout);
        APLayout.setHorizontalGroup(
            APLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(APLayout.createSequentialGroup()
                .addComponent(AL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        APLayout.setVerticalGroup(
            APLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AL, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel1.add(AP);
        AP.setBounds(1014, 479, 180, 50);

        REP.setBackground(new java.awt.Color(255, 255, 255));
        REP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        REP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        REP.setPreferredSize(new java.awt.Dimension(180, 53));
        REP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                REPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                REPMouseExited(evt);
            }
        });

        REL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 13)); // NOI18N
        REL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        REL.setText("REGISTER");
        REL.setPreferredSize(new java.awt.Dimension(180, 53));

        javax.swing.GroupLayout REPLayout = new javax.swing.GroupLayout(REP);
        REP.setLayout(REPLayout);
        REPLayout.setHorizontalGroup(
            REPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(REL, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        REPLayout.setVerticalGroup(
            REPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(REL, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(REP);
        REP.setBounds(1016, 550, 180, 53);

        RP.setBackground(new java.awt.Color(255, 255, 255));
        RP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        RP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RP.setPreferredSize(new java.awt.Dimension(183, 53));

        RL.setBackground(new java.awt.Color(255, 255, 255));
        RL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        RL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RL.setText("RETURN");
        RL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout RPLayout = new javax.swing.GroupLayout(RP);
        RP.setLayout(RPLayout);
        RPLayout.setHorizontalGroup(
            RPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        );
        RPLayout.setVerticalGroup(
            RPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jPanel1.add(RP);
        RP.setBounds(1018, 670, 183, 53);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_info/add info.jpg"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 1280, 770);

        imt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        imt.setText("jTextField1");
        jPanel1.add(imt);
        imt.setBounds(980, 400, 270, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1280, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALMouseClicked
        JFileChooser ch=new JFileChooser();
        ch.showOpenDialog(null);
        File f=ch.getSelectedFile();
        String fn=f.getAbsolutePath();
        ImageIcon imc=new ImageIcon(new ImageIcon(fn).getImage().getScaledInstance(img.getWidth(),img.getHeight(),Image.SCALE_SMOOTH));
        img.setIcon(imc);
        imt.setText(fn);
    }//GEN-LAST:event_ALMouseClicked

    private void ALMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALMouseEntered
        AL.setForeground(Color.WHITE);
        AP.setBackground(new Color(255,51,51));
        AP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_ALMouseEntered

    private void ALMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALMouseExited
        AL.setForeground(new Color(0,0,0));
        AP.setBackground(Color.WHITE);
        AP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_ALMouseExited

    private void RLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RLMouseClicked
        Menu_page mn=new Menu_page();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RLMouseClicked

    private void RLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RLMouseEntered
        RL.setForeground(Color.WHITE);
        RP.setBackground(new Color(255,51,51));
        RP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_RLMouseEntered

    private void RLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RLMouseExited
      RL.setForeground(new Color(0,0,0));
        RP.setBackground(Color.WHITE);
        RP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_RLMouseExited
private int xMouse,yMouse;
    private void DPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DPMouseDragged
       int x=evt.getXOnScreen();
       int y=evt.getYOnScreen();
       setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_DPMouseDragged

    private void DPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DPMousePressed
       xMouse=evt.getX();
       yMouse=evt.getY();
    }//GEN-LAST:event_DPMousePressed

    private void REPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REPMouseClicked
       String nm=nm1.getText();
       String cl=c1.getText();
       String dob=d1.getText();
       String sch=s1.getText();
       int pn=Integer.parseInt(p1.getText());
       String ad=ta1.getText();
       String ct=ct1.getText();
       String ed=e1.getText();
       Long mb=Long.parseLong(m1.getText());
       String b="";
       String g="";
       String im=imt.getText();
       int id=Integer.parseInt(id1.getText());
       if(rb1.isSelected())
       {
           b="CBSE";
       }
       else if(rb2.isSelected())
       {
         b="ICSE";          
       }
       if(rb3.isSelected())
       {
           g="MALE";
       }
       else if(rb4.isSelected())
       {
           g="FEMALE";
       }
        try
        {
            
           Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
           String qa="Select * from records where idn=?";
           PreparedStatement ps=con.prepareStatement(qa);
           ps.setInt(1,id);
           ResultSet rs=ps.executeQuery();
           if(rs.next())
           {
                JOptionPane.showMessageDialog(this,"This IDNO already exists","Warning",JOptionPane.WARNING_MESSAGE);
                nm1.setText("");
                 c1.setText("");
                  d1.setText("");
                    ta1.setText("");
                      e1.setText("");
                       p1.setText("");
                        m1.setText("");
                         s1.setText("");
                          ct1.setText("");
                          buttonGroup1.clearSelection();
                            buttonGroup2.clearSelection();
                            imt.setText("");
                             id1.setText("");
                             img.setIcon(null);
                            
          con.close();
          rs.close();
          }
          
           im=im.replace("\\","\\\\");
           PreparedStatement pst=null;
           pst=con.prepareStatement("insert into records values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
           pst.setInt(1,id);
           pst.setString(2,nm);
           pst.setString(3,cl );
           pst.setString(4,dob);
           pst.setString(5,g);
           pst.setString(6,sch);
           pst.setString(7,b);
           pst.setString(8,ad);
           pst.setString(9,ct);
           pst.setInt(10,pn);
           pst.setLong(11,mb);
           pst.setString(12,ed);
           pst.setString(13,im);
           int i=pst.executeUpdate();
            if (i>0)
           {
               JOptionPane.showMessageDialog(null,"Your record has been successfully saved ");
                nm1.setText("");
                 c1.setText("");
                  d1.setText("");
                    ta1.setText("");
                      e1.setText("");
                       p1.setText("");
                        m1.setText("");
                         s1.setText("");
                          ct1.setText("");
                          buttonGroup1.clearSelection();
                            buttonGroup2.clearSelection();
                           img.setIcon(null);
                            imt.setText("");
                            id1.setText("");
           }

           
        }
           catch(Exception e)
                   {
                   System.out.println(e);
                   }
    }//GEN-LAST:event_REPMouseClicked

    private void REPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REPMouseEntered
        REL.setForeground(Color.WHITE);
        REP.setBackground(new Color(255,51,51));
        REP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_REPMouseEntered

    private void REPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REPMouseExited
       REL.setForeground(new Color(0,0,0));
        REP.setBackground(Color.WHITE);
        REP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_REPMouseExited

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m1ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void nm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nm1ActionPerformed

    private void nm1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nm1KeyReleased
        String nm=nm1.getText();
        String nam=nm.toUpperCase();
        if(nm.equals(nam))
        {
            nm1.setText(nm);
        }
        else{
            JOptionPane.showMessageDialog(this,"PLEASE ENTER IN BLOCK LETTERS","Warning",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_nm1KeyReleased

    private void e1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e1KeyReleased
        String e=e1.getText();
        String ed=e.toLowerCase();
        if(e.equals(ed))
        {
            e1.setText(e);
        }
        else{
            JOptionPane.showMessageDialog(this,"PLEASE ENTER IN SMALL LETTERS","Warning",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_e1KeyReleased

    private void nm1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nm1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nm1KeyTyped

    private void id1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id1KeyReleased
     
    }//GEN-LAST:event_id1KeyReleased

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addinfo_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AL;
    private javax.swing.JPanel AP;
    private javax.swing.JPanel DP;
    private javax.swing.JLabel REL;
    private javax.swing.JPanel REP;
    private javax.swing.JLabel RL;
    private javax.swing.JPanel RP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField ct1;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField id1;
    private javax.swing.JLabel img;
    private javax.swing.JTextField imt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField nm1;
    private javax.swing.JTextField p1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JTextField s1;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
