
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Delete extends javax.swing.JFrame {
Connection con=null;
    Statement st=null;
    ResultSet rs= null;
    
    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
        ne.setEditable(false);
        cls.setEditable(false);
        pin.setEditable(false);
        db.setEditable(false);
        sch.setEditable(false);
        mb.setEditable(false);
        emd.setEditable(false);
        add.setEditable(false);
        cit.setEditable(false);
        rb1.setSelected(false);
         rb2.setSelected(false);
          rb3.setSelected(false);
           rb4.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        DP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ne = new javax.swing.JTextField();
        cls = new javax.swing.JTextField();
        db = new javax.swing.JTextField();
        sch = new javax.swing.JTextField();
        rb2 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        cit = new javax.swing.JTextField();
        mb = new javax.swing.JTextField();
        emd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        SP = new javax.swing.JPanel();
        SL = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        img = new javax.swing.JLabel();
        DEP = new javax.swing.JPanel();
        DEL = new javax.swing.JLabel();
        RP = new javax.swing.JPanel();
        RL = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        imgt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 7));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 770));
        jPanel1.setLayout(null);

        DP.setBackground(new java.awt.Color(0, 51, 51));
        DP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DPMouseDragged(evt);
            }
        });
        DP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DPMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DELETE");

        javax.swing.GroupLayout DPLayout = new javax.swing.GroupLayout(DP);
        DP.setLayout(DPLayout);
        DPLayout.setHorizontalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351))
        );
        DPLayout.setVerticalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(DP);
        DP.setBounds(7, 7, 1266, 121);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(581, 300));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" NAME");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" CLASS");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" DOB");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" SCHOOL");

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" BOARD");

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" ADDRESS");

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" MOBILE NO");

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" CITY");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" E-mail ID");

        ne.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ne.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        cls.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cls.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        db.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        db.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        sch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        rb2.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        rb2.setForeground(new java.awt.Color(255, 255, 255));
        rb2.setText("ICSE");

        rb1.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        rb1.setForeground(new java.awt.Color(255, 255, 255));
        rb1.setText("CBSE");

        add.setColumns(20);
        add.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add.setRows(5);
        add.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jScrollPane1.setViewportView(add);

        cit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cit.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        mb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mb.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        mb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbActionPerformed(evt);
            }
        });

        emd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emd.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" GENDER");

        rb3.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(rb3);
        rb3.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        rb3.setForeground(new java.awt.Color(255, 255, 255));
        rb3.setText("MALE");

        rb4.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(rb4);
        rb4.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        rb4.setForeground(new java.awt.Color(255, 255, 255));
        rb4.setText("FEMALE");

        jLabel14.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" PINCODE");

        pin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        SP.setBackground(new java.awt.Color(255, 255, 255));
        SP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        SP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SP.setPreferredSize(new java.awt.Dimension(133, 44));

        SL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        SL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SL.setText("SEARCH");
        SL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SPLayout = new javax.swing.GroupLayout(SP);
        SP.setLayout(SPLayout);
        SPLayout.setHorizontalGroup(
            SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SL, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        SPLayout.setVerticalGroup(
            SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SL, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" ID NO");

        id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        id.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emd, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mb, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cit, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ne, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sch, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(db, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(rb3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(rb4))
                                            .addComponent(cls, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cls, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ne, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(db, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sch, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(cit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(17, 139, 937, 613);

        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel1.add(img);
        img.setBounds(980, 139, 254, 238);

        DEP.setBackground(new java.awt.Color(255, 255, 255));
        DEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        DEP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DEP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DEPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DEPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DEPMouseExited(evt);
            }
        });

        DEL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 13)); // NOI18N
        DEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DEL.setText("DELETE");

        javax.swing.GroupLayout DEPLayout = new javax.swing.GroupLayout(DEP);
        DEP.setLayout(DEPLayout);
        DEPLayout.setHorizontalGroup(
            DEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DEL, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        DEPLayout.setVerticalGroup(
            DEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DEPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DEL, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(DEP);
        DEP.setBounds(1016, 550, 180, 53);

        RP.setBackground(new java.awt.Color(255, 255, 255));
        RP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        RP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RP.setPreferredSize(new java.awt.Dimension(133, 44));

        RL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        RL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RL.setText("RETURN");
        RL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout RPLayout = new javax.swing.GroupLayout(RP);
        RP.setLayout(RPLayout);
        RPLayout.setHorizontalGroup(
            RPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        );
        RPLayout.setVerticalGroup(
            RPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jPanel1.add(RP);
        RP.setBounds(1018, 670, 183, 53);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_info/delete.jpg"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 1280, 770);

        imgt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        imgt.setText("jTextField9");
        jPanel1.add(imgt);
        imgt.setBounds(979, 400, 270, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1280, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   private int xMouse,yMouse;
    private void DPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DPMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_DPMouseDragged

    private void DPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DPMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_DPMousePressed

    private void SLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SLMouseClicked
          String bo="";
        String ge="";
        try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
            st=con.createStatement();
            String q="Select * from records where idn=" +id.getText()+";";
            rs=st.executeQuery(q);
            if(rs.next())
            {
               int i=rs.getInt("idn");
               String nm=rs.getString("name");
               String c=rs.getString("class");
               String d=rs.getString("dob");
               String g=rs.getString("gender");
               String s=rs.getString("school");
               String b=rs.getString("board");
               String ad=rs.getString("address");
               String ct=rs.getString("city");
               int  p=rs.getInt("pincode");
               Long m=rs.getLong("mobile_no");
               String e=rs.getString("email");
               String im=rs.getString("image");
               ImageIcon ic=new ImageIcon(im);
               Image ima=ic.getImage();
               Image image=ima.getScaledInstance(img.getWidth(),img.getHeight(),Image.SCALE_SMOOTH);
               ImageIcon nim=new ImageIcon(image);
               img.setIcon(nim);
               
               
               ne.setText(nm);
               cls.setText(c);
               db.setText(d);
               if("MALE".equals(g))
               {
                   rb3.setSelected(true);
               }
               else if("FEMALE".equals(g))
               {
                   rb4.setSelected(true);
               }
               sch.setText(s);
                if("CBSE".equals(b))
               {
                   rb1.setSelected(true);
               }
               else if("ICSE".equals(b))
               {
                   rb2.setSelected(true);
               }
               add.setText(ad);
               cit.setText(ct);
               pin.setText(""+p);
               mb.setText(""+m);
               emd.setText(e);
              }
            else
            {
                JOptionPane.showMessageDialog(this,"NO such record found","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_SLMouseClicked

    private void SLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SLMouseEntered
        SL.setForeground(Color.WHITE);
        SP.setBackground(new Color(255,51,51));
        SP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_SLMouseEntered

    private void SLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SLMouseExited
        SL.setForeground(new Color(0,0,0));
        SP.setBackground(Color.WHITE);
        SP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_SLMouseExited

    private void DEPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DEPMouseClicked
      String idno=id.getText();
            
        try  
       {
           st=con.createStatement();
           String qe="DELETE from records where idn="+idno+";";
           st.executeUpdate(qe);
           JOptionPane.showMessageDialog(null,"Your record has been deleted successfully");
            id.setText("");
                ne.setText("");
                 db.setText("");
                  cls.setText("");
                   sch.setText("");
                    emd.setText("");
                     add.setText("");
                      mb.setText("");
                      imgt.setText("");
                         cit.setText("");
                          pin.setText("");
                          img.setIcon(null);
                        buttonGroup1.clearSelection();
                        buttonGroup2.clearSelection();
       }
       catch(Exception ex)
       {
           System.out.println(ex);
       }
      
     
    }//GEN-LAST:event_DEPMouseClicked

    private void DEPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DEPMouseEntered
        DEL.setForeground(Color.WHITE);
        DEP.setBackground(new Color(255,51,51));
        DEP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_DEPMouseEntered

    private void DEPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DEPMouseExited
        DEL.setForeground(new Color(0,0,0));
        DEP.setBackground(Color.WHITE);
        DEP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_DEPMouseExited

    private void RLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RLMouseClicked
        Menu_page mn=new Menu_page();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RLMouseClicked

    private void RLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RLMouseEntered
        RL.setForeground(Color.WHITE);
        RP.setBackground(new Color(255,51,51));
        RP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_RLMouseEntered

    private void RLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RLMouseExited
        RL.setForeground(new Color(0,0,0));
        RP.setBackground(Color.WHITE);
        RP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_RLMouseExited

    private void mbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DEL;
    private javax.swing.JPanel DEP;
    private javax.swing.JPanel DP;
    private javax.swing.JLabel RL;
    private javax.swing.JPanel RP;
    private javax.swing.JLabel SL;
    private javax.swing.JPanel SP;
    private javax.swing.JTextArea add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cit;
    private javax.swing.JTextField cls;
    private javax.swing.JTextField db;
    private javax.swing.JTextField emd;
    private javax.swing.JTextField id;
    private javax.swing.JLabel img;
    private javax.swing.JTextField imgt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mb;
    private javax.swing.JTextField ne;
    private javax.swing.JTextField pin;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JTextField sch;
    // End of variables declaration//GEN-END:variables
}
