
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Menu_page extends javax.swing.JFrame {

    /**
     * Creates new form Menu_page
     */
    public Menu_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        DGP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AP = new javax.swing.JPanel();
        AL = new javax.swing.JLabel();
        MP = new javax.swing.JPanel();
        ML = new javax.swing.JLabel();
        DP = new javax.swing.JPanel();
        DL = new javax.swing.JLabel();
        ABP = new javax.swing.JPanel();
        ABL = new javax.swing.JLabel();
        SP = new javax.swing.JPanel();
        SL = new javax.swing.JLabel();
        EP = new javax.swing.JPanel();
        EL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setUndecorated(true);
        setOpacity(0.9F);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 7));

        DGP.setBackground(new java.awt.Color(0, 102, 102));
        DGP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DGPMouseDragged(evt);
            }
        });
        DGP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DGPMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIMEX TUTORIAL");

        javax.swing.GroupLayout DGPLayout = new javax.swing.GroupLayout(DGP);
        DGP.setLayout(DGPLayout);
        DGPLayout.setHorizontalGroup(
            DGPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DGPLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DGPLayout.setVerticalGroup(
            DGPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DGPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(306, 428));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" - guided by ");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 29)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RAJU PRATAP SINGH");

        jLabel7.setFont(new java.awt.Font("Terminator Two", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Only a good teacher inspire hope  ");

        jLabel8.setFont(new java.awt.Font("Terminator Two", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ignite the imagination ...");

        jLabel9.setFont(new java.awt.Font("Terminator Two", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("and instill a love of learning ...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        AP.setBackground(new java.awt.Color(255, 255, 255));
        AP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        AP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AL.setBackground(new java.awt.Color(255, 255, 255));
        AL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        AL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AL.setText("ADD RECORD");
        AL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ALMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ALMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ALMouseExited(evt);
            }
        });

        javax.swing.GroupLayout APLayout = new javax.swing.GroupLayout(AP);
        AP.setLayout(APLayout);
        APLayout.setHorizontalGroup(
            APLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        APLayout.setVerticalGroup(
            APLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        MP.setBackground(new java.awt.Color(255, 255, 255));
        MP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 153, 51)));
        MP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MP.setPreferredSize(new java.awt.Dimension(204, 50));

        ML.setBackground(new java.awt.Color(255, 255, 255));
        ML.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        ML.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ML.setText("MODIFY RECORD");
        ML.setPreferredSize(new java.awt.Dimension(204, 50));
        ML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MPLayout = new javax.swing.GroupLayout(MP);
        MP.setLayout(MPLayout);
        MPLayout.setHorizontalGroup(
            MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ML, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );
        MPLayout.setVerticalGroup(
            MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ML, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        DP.setBackground(new java.awt.Color(255, 255, 255));
        DP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 153, 51)));
        DP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DP.setPreferredSize(new java.awt.Dimension(204, 50));

        DL.setBackground(new java.awt.Color(255, 255, 255));
        DL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        DL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DL.setText("DELETE RECORD");
        DL.setPreferredSize(new java.awt.Dimension(204, 50));
        DL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout DPLayout = new javax.swing.GroupLayout(DP);
        DP.setLayout(DPLayout);
        DPLayout.setHorizontalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DPLayout.setVerticalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DL, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        ABP.setBackground(new java.awt.Color(255, 255, 255));
        ABP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 153, 51)));
        ABP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ABP.setPreferredSize(new java.awt.Dimension(204, 50));

        ABL.setBackground(new java.awt.Color(255, 255, 255));
        ABL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        ABL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ABL.setText("ABOUT SOFTWARE");
        ABL.setPreferredSize(new java.awt.Dimension(204, 50));
        ABL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ABLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ABLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ABLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ABPLayout = new javax.swing.GroupLayout(ABP);
        ABP.setLayout(ABPLayout);
        ABPLayout.setHorizontalGroup(
            ABPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ABPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ABL, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ABPLayout.setVerticalGroup(
            ABPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ABPLayout.createSequentialGroup()
                .addComponent(ABL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        SP.setBackground(new java.awt.Color(255, 255, 255));
        SP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 153, 51)));
        SP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SP.setPreferredSize(new java.awt.Dimension(204, 50));

        SL.setBackground(new java.awt.Color(255, 255, 255));
        SL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        SL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SL.setText("SHOW ALL RECORD");
        SL.setPreferredSize(new java.awt.Dimension(204, 50));
        SL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SPLayout = new javax.swing.GroupLayout(SP);
        SP.setLayout(SPLayout);
        SPLayout.setHorizontalGroup(
            SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SL, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SPLayout.setVerticalGroup(
            SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        EP.setBackground(new java.awt.Color(255, 255, 255));
        EP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 153, 51)));
        EP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EP.setPreferredSize(new java.awt.Dimension(200, 50));

        EL.setBackground(new java.awt.Color(255, 255, 255));
        EL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        EL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EL.setText("EXIT");
        EL.setPreferredSize(new java.awt.Dimension(204, 50));
        EL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ELMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ELMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ELMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EPLayout = new javax.swing.GroupLayout(EP);
        EP.setLayout(EPLayout);
        EPLayout.setHorizontalGroup(
            EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EL, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        );
        EPLayout.setVerticalGroup(
            EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel3.setText(" For - VI , VII , VIII , IX , X ");

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel4.setText("( ALL SUBJECTS )");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText(" CBSE / ICSE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DGP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ABP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(EP, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(176, 176, 176))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(AP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DP, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(DGP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(ABP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(EP, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALMouseClicked
       Addinfo_page ad=new Addinfo_page();
       ad.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ALMouseClicked

    private void ALMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALMouseEntered
        AL.setForeground(Color.WHITE);
        AP.setBackground(new Color(255,51,51));
        AP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_ALMouseEntered

    private void ALMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALMouseExited
        AL.setForeground(new Color(0,0,0));
        AP.setBackground(Color.WHITE);
        AP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_ALMouseExited

    private void MLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MLMouseClicked
        Modify md=new Modify();
        md.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MLMouseClicked

    private void MLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MLMouseEntered
         ML.setForeground(Color.WHITE);
        MP.setBackground(new Color(255,51,51));
        MP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_MLMouseEntered

    private void MLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MLMouseExited
         ML.setForeground(new Color(0,0,0));
        MP.setBackground(Color.WHITE);
        MP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_MLMouseExited

    private void DLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DLMouseClicked
        Delete dl=new Delete();
        dl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DLMouseClicked

    private void DLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DLMouseEntered
        DL.setForeground(Color.WHITE);
        DP.setBackground(new Color(255,51,51));
        DP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_DLMouseEntered

    private void DLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DLMouseExited
        DL.setForeground(new Color(0,0,0));
        DP.setBackground(Color.WHITE);
        DP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_DLMouseExited

    private void ABLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ABLMouseClicked
       About ab=new About();
       ab.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ABLMouseClicked

    private void ABLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ABLMouseEntered
       ABL.setForeground(Color.WHITE);
        ABP.setBackground(new Color(255,51,51));
        ABP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_ABLMouseEntered

    private void ABLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ABLMouseExited
        ABL.setForeground(new Color(0,0,0));
        ABP.setBackground(Color.WHITE);
        ABP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_ABLMouseExited

    private void SLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SLMouseClicked
        All_Records al=new All_Records();
        al.setVisible(true);
        this.dispose();
                
                
    }//GEN-LAST:event_SLMouseClicked

    private void SLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SLMouseEntered
      SL.setForeground(Color.WHITE);
        SP.setBackground(new Color(255,51,51));
        SP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_SLMouseEntered

    private void SLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SLMouseExited
         SL.setForeground(new Color(0,0,0));
        SP.setBackground(Color.WHITE);
        SP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_SLMouseExited

    private void ELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ELMouseClicked
      int ans=JOptionPane.showConfirmDialog(this,"Do you really want to Exit");
      if(ans==JOptionPane.YES_OPTION)
      {
         this.dispose();
      }
      
        
    }//GEN-LAST:event_ELMouseClicked

    private void ELMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ELMouseEntered
       EL.setForeground(Color.WHITE);
       EP.setBackground(new Color(255,51,51));
        EP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_ELMouseEntered

    private void ELMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ELMouseExited
          EL.setForeground(new Color(0,0,0));
        EP.setBackground(Color.WHITE);
        EP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_ELMouseExited
private int xMouse,yMouse;
    private void DGPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DGPMouseDragged
      int x=evt.getXOnScreen();
       int y=evt.getYOnScreen();
       setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_DGPMouseDragged

    private void DGPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DGPMousePressed
       xMouse=evt.getX();
       yMouse=evt.getY();
    }//GEN-LAST:event_DGPMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ABL;
    private javax.swing.JPanel ABP;
    private javax.swing.JLabel AL;
    private javax.swing.JPanel AP;
    private javax.swing.JPanel DGP;
    private javax.swing.JLabel DL;
    private javax.swing.JPanel DP;
    private javax.swing.JLabel EL;
    private javax.swing.JPanel EP;
    private javax.swing.JLabel ML;
    private javax.swing.JPanel MP;
    private javax.swing.JLabel SL;
    private javax.swing.JPanel SP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
