
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.border.LineBorder;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Modify extends javax.swing.JFrame {
    Connection con=null;
    Statement st=null;
    ResultSet rs= null;
    /**
     * Creates new form Modify
     */
    public Modify() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        DP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        na = new javax.swing.JTextField();
        cl = new javax.swing.JTextField();
        db = new javax.swing.JTextField();
        sc = new javax.swing.JTextField();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        cty = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        pn = new javax.swing.JTextField();
        SP = new javax.swing.JPanel();
        SL = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        idno = new javax.swing.JTextField();
        img = new javax.swing.JLabel();
        CHP = new javax.swing.JPanel();
        CHL = new javax.swing.JLabel();
        MP = new javax.swing.JPanel();
        ML = new javax.swing.JLabel();
        RP = new javax.swing.JPanel();
        RL = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        imgt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 7));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 770));
        jPanel1.setLayout(null);

        DP.setBackground(new java.awt.Color(0, 51, 51));
        DP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DPMouseDragged(evt);
            }
        });
        DP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DPMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MODIFY");

        javax.swing.GroupLayout DPLayout = new javax.swing.GroupLayout(DP);
        DP.setLayout(DPLayout);
        DPLayout.setHorizontalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351))
        );
        DPLayout.setVerticalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(DP);
        DP.setBounds(7, 7, 1266, 121);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(581, 300));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" ID NO");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" CLASS");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" DOB");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" SCHOOL");

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" BOARD");

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" ADDRESS");

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" MOBILE NO");

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" CITY");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" E-mail ID");

        na.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        na.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        na.setEnabled(false);
        na.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                naKeyReleased(evt);
            }
        });

        cl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        cl.setEnabled(false);

        db.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        db.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        db.setEnabled(false);

        sc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        sc.setEnabled(false);

        r2.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("ICSE");
        r2.setEnabled(false);

        r1.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("CBSE");
        r1.setEnabled(false);

        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ta.setRows(5);
        ta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        ta.setEnabled(false);
        jScrollPane1.setViewportView(ta);

        cty.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cty.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        cty.setEnabled(false);

        mob.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mob.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        mob.setEnabled(false);

        em.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        em.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        em.setEnabled(false);
        em.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" GENDER");

        r3.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(r3);
        r3.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.setText("MALE");
        r3.setEnabled(false);

        r4.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(r4);
        r4.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        r4.setForeground(new java.awt.Color(255, 255, 255));
        r4.setText("FEMALE");
        r4.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" PINCODE");

        pn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        pn.setEnabled(false);
        pn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnActionPerformed(evt);
            }
        });

        SP.setBackground(new java.awt.Color(255, 255, 255));
        SP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        SP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SP.setPreferredSize(new java.awt.Dimension(133, 44));

        SL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        SL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SL.setText("SEARCH");
        SL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SPLayout = new javax.swing.GroupLayout(SP);
        SP.setLayout(SPLayout);
        SPLayout.setHorizontalGroup(
            SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SL, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        SPLayout.setVerticalGroup(
            SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SL, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" NAME");

        idno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        idno.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mob, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cty, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(na, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(db, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idno, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cl, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addComponent(r4))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(idno)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(na, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(3, 3, 3)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(db, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(r4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pn)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cty, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mob, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(17, 139, 937, 613);

        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        img.setEnabled(false);
        jPanel1.add(img);
        img.setBounds(980, 139, 254, 238);

        CHP.setBackground(new java.awt.Color(255, 255, 255));
        CHP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        CHP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CHP.setPreferredSize(new java.awt.Dimension(180, 53));

        CHL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        CHL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CHL.setText("CHANGE PHOTO");
        CHL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CHLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CHLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CHLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CHPLayout = new javax.swing.GroupLayout(CHP);
        CHP.setLayout(CHPLayout);
        CHPLayout.setHorizontalGroup(
            CHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CHPLayout.createSequentialGroup()
                .addComponent(CHL, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CHPLayout.setVerticalGroup(
            CHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CHL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jPanel1.add(CHP);
        CHP.setBounds(1014, 469, 180, 53);

        MP.setBackground(new java.awt.Color(255, 255, 255));
        MP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        MP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MPMouseExited(evt);
            }
        });

        ML.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 13)); // NOI18N
        ML.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ML.setText("MODIFY");

        javax.swing.GroupLayout MPLayout = new javax.swing.GroupLayout(MP);
        MP.setLayout(MPLayout);
        MPLayout.setHorizontalGroup(
            MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ML, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        MPLayout.setVerticalGroup(
            MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ML, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(MP);
        MP.setBounds(1016, 550, 180, 53);

        RP.setBackground(new java.awt.Color(255, 255, 255));
        RP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        RP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RP.setPreferredSize(new java.awt.Dimension(133, 44));

        RL.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        RL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RL.setText("RETURN");
        RL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout RPLayout = new javax.swing.GroupLayout(RP);
        RP.setLayout(RPLayout);
        RPLayout.setHorizontalGroup(
            RPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        );
        RPLayout.setVerticalGroup(
            RPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jPanel1.add(RP);
        RP.setBounds(1018, 670, 183, 53);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_info/modify.jpg"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 1280, 770);

        imgt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        imgt.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.add(imgt);
        imgt.setBounds(980, 400, 270, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1280, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       private int xMouse, yMouse;
    private void DPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DPMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_DPMouseDragged

    private void DPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DPMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_DPMousePressed

    private void CHLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHLMouseClicked
        JFileChooser cho=new JFileChooser();
        cho.showOpenDialog(null);
        File fl=cho.getSelectedFile();
        String fln=fl.getAbsolutePath();
        ImageIcon imcn=new ImageIcon(new ImageIcon(fln).getImage().getScaledInstance(img.getWidth(),img.getHeight(),Image.SCALE_SMOOTH));
        img.setIcon(imcn);
        imgt.setText(fln);
    }//GEN-LAST:event_CHLMouseClicked

    private void CHLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHLMouseEntered
        CHL.setForeground(Color.WHITE);
        CHP.setBackground(new Color(255,51,51));
        CHP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_CHLMouseEntered

    private void CHLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHLMouseExited
        CHL.setForeground(new Color(0,0,0));
        CHP.setBackground(Color.WHITE);
        CHP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_CHLMouseExited

    private void RLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RLMouseClicked
        Menu_page mn=new Menu_page();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RLMouseClicked

    private void RLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RLMouseEntered
        RL.setForeground(Color.WHITE);
        RP.setBackground(new Color(255,51,51));
        RP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_RLMouseEntered

    private void RLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RLMouseExited
        RL.setForeground(new Color(0,0,0));
        RP.setBackground(Color.WHITE);
        RP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_RLMouseExited

    private void SLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SLMouseClicked
        String bo="";
        String ge="";
        try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
            st=con.createStatement();
            String q="Select * from records where idn=" +idno.getText()+";";
            rs=st.executeQuery(q);
            if(rs.next())
            {
               int i=rs.getInt("idn");
               String nm=rs.getString("name");
               String c=rs.getString("class");
               String d=rs.getString("dob");
               String g=rs.getString("gender");
               String s=rs.getString("school");
               String b=rs.getString("board");
               String ad=rs.getString("address");
               String ct=rs.getString("city");
               int  p=rs.getInt("pincode");
               Long m=rs.getLong("mobile_no");
               String e=rs.getString("email");
               String im=rs.getString("image");
               ImageIcon ic=new ImageIcon(im);
               Image ima=ic.getImage();
               Image image=ima.getScaledInstance(img.getWidth(),img.getHeight(),Image.SCALE_SMOOTH);
               ImageIcon nim=new ImageIcon(image);
               img.setIcon(nim);
               
               
               na.setText(nm);
               cl.setText(c);
               db.setText(d);
               if("MALE".equals(g))
               {
                   r3.setSelected(true);
               }
               else if("FEMALE".equals(g))
               {
                   r4.setSelected(true);
               }
               sc.setText(s);
                if("CBSE".equals(b))
               {
                   r1.setSelected(true);
               }
               else if("ICSE".equals(b))
               {
                   r2.setSelected(true);
               }
               ta.setText(ad);
               cty.setText(ct);
               pn.setText(""+p);
               mob.setText(""+m);
               em.setText(e);
               
            
               
               na.setEnabled(true);
                cl.setEnabled(true);
                 db.setEnabled(true);
                   r1.setEnabled(true);
                   r2.setEnabled(true);
                    r3.setEnabled(true);
                     r4.setEnabled(true);
                      cty.setEnabled(true);
                       mob.setEnabled(true);
                        pn.setEnabled(true);
                         sc.setEnabled(true);
                          em.setEnabled(true);
                           imgt.setEnabled(true);
                            ta.setEnabled(true);
                              img.setEnabled(true);
               
            }
            else
            {
                JOptionPane.showMessageDialog(this,"NO such record found","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_SLMouseClicked

    private void SLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SLMouseEntered
        SL.setForeground(Color.WHITE);
        SP.setBackground(new Color(255,51,51));
        SP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_SLMouseEntered

    private void SLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SLMouseExited
        SL.setForeground(new Color(0,0,0));
        SP.setBackground(Color.WHITE);
       SP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_SLMouseExited

    private void MPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MPMouseClicked
          int i=Integer.parseInt(idno.getText());
          String n=na.getText();
          String c=cl.getText();
          String dob=db.getText();
          String gn="";
          String br="";
          if(r1.isSelected())
          {
             br="CBSE"; 
          }
          else if(r2.isSelected())
          {
              br="ICSE";
          }
          if(r3.isSelected())
          {
             gn="MALE"; 
          }
          else if(r4.isSelected())
          {
             gn="FEMALE";
          }
          String s=sc.getText();
          String ad=ta.getText();
          String ci=cty.getText();
          int pi=Integer.parseInt(pn.getText());
          Long m=Long.parseLong(mob.getText());
          String ed=em.getText();
          String imge=imgt.getText();
          try
           {
               imge=imge.replace("\\","\\\\");
               st=con.createStatement();
               String qe="UPDATE records set name='"+n+"',class='"+c+"',dob='"+dob+"',gender='"+gn+"',school='"+s+"',board='"+br+"',address='"+ad+"',city='"+ci+"',pincode='"+pi+"',mobile_no='"+m+"',email='"+ed+"',image='"+imge+"' where idn="+i+";";
               st.executeUpdate(qe);
               JOptionPane.showMessageDialog(null,"Your record has been updated successfully");
               idno.setText("");
                na.setText("");
                 db.setText("");
                  cl.setText("");
                   sc.setText("");
                    em.setText("");
                     ta.setText("");
                      mob.setText("");
                       img.setText("");
                        imgt.setText("");
                         cty.setText("");
                          pn.setText("");
                           img.setIcon(null);
                        buttonGroup1.clearSelection();
                        buttonGroup2.clearSelection();
               
            }
           catch(Exception e)
           {
               System.out.println(e);
           }
    }//GEN-LAST:event_MPMouseClicked

    private void MPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MPMouseEntered
        ML.setForeground(Color.WHITE);
        MP.setBackground(new Color(255,51,51));
        MP.setBorder(new LineBorder(new Color(255,51,51),1,true));
    }//GEN-LAST:event_MPMouseEntered

    private void MPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MPMouseExited
        ML.setForeground(new Color(0,0,0));
        MP.setBackground(Color.WHITE);
        MP.setBorder(new LineBorder(new Color(255,153,51),1,true));
    }//GEN-LAST:event_MPMouseExited

    private void pnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnActionPerformed

    private void naKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_naKeyReleased
         String nm=na.getText();
        String nam=nm.toUpperCase();
        if(nm.equals(nam))
        {
            na.setText(nm);
        }
        else{
            JOptionPane.showMessageDialog(this,"PLEASE ENTER IN BLOCK LETTERS","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_naKeyReleased

    private void emKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emKeyReleased
    String e=em.getText();
        String ed=e.toLowerCase();
        if(e.equals(ed))
        {
            em.setText(e);
        }
        else{
            JOptionPane.showMessageDialog(this,"PLEASE ENTER IN SMALL LETTERS","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_emKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CHL;
    private javax.swing.JPanel CHP;
    private javax.swing.JPanel DP;
    private javax.swing.JLabel ML;
    private javax.swing.JPanel MP;
    private javax.swing.JLabel RL;
    private javax.swing.JPanel RP;
    private javax.swing.JLabel SL;
    private javax.swing.JPanel SP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cl;
    private javax.swing.JTextField cty;
    private javax.swing.JTextField db;
    private javax.swing.JTextField em;
    private javax.swing.JTextField idno;
    private javax.swing.JLabel img;
    private javax.swing.JTextField imgt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField na;
    private javax.swing.JTextField pn;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JTextField sc;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
